// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tost_dp_one_sample_ultra_fast
List tost_dp_one_sample_ultra_fast(double a, double b, int n, double epsilon, double mean_private_obs, double sd_private_obs, double lower, double upper, int B, double alpha, int seed);
RcppExport SEXP _cTOST_tost_dp_one_sample_ultra_fast(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP epsilonSEXP, SEXP mean_private_obsSEXP, SEXP sd_private_obsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP BSEXP, SEXP alphaSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type mean_private_obs(mean_private_obsSEXP);
    Rcpp::traits::input_parameter< double >::type sd_private_obs(sd_private_obsSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(tost_dp_one_sample_ultra_fast(a, b, n, epsilon, mean_private_obs, sd_private_obs, lower, upper, B, alpha, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cTOST_tost_dp_one_sample_ultra_fast", (DL_FUNC) &_cTOST_tost_dp_one_sample_ultra_fast, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_cTOST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
